Algoritmo "digitar e imprimir"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2022
Var
n1,n2 :real




Inicio
escreva("digite um numero")
leia (n1)
escreva ("digite outro numero")
leia (n2)
se(n1 >= n2)entao
escreva(n1)
fimse
se( n2 >= n1) entao
escreva(n2)
fimse



Fimalgoritmo