Algoritmo "faixa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
f1: real


Inicio
escreval("digite um número")
leia(f1)
se(f1 >=1) e (f1<=9)entao
escreval("está na faixa")
senao
escreval("não está na faixa")
fimse


Fimalgoritmo