Algoritmo "maior número"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
n1,n2: real

Inicio
escreval("digite um número")
leia(n1)
escreval("digite outro número")
leia(n2)
se (n1 > N2)entao
escreval("o maior número é:", n1)
senao
escreval("o maior número é:", n2)
fimse

Fimalgoritmo