Algoritmo "média de 2 notas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
n1,n2,s1,m1: real


Inicio
escreval("digite a primeira nota")
leia(n1)
escreval("digite a nota 2")
leia(n2)
s1 <- (n1+n2)
m1 <- (s1/2)
escreval("sua média final foi:",m1)

Fimalgoritmo