Algoritmo "Soma de dois numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
n1,n2,n3: real


Inicio
escreval("digite um número")
leia(n1)
escreval("digite ooutro número")
leia(n2)
n3<-(n1+n2)
escreval("a soma dos dois números é:",n3)


Fimalgoritmo