Algoritmo "temperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
t1:real

Inicio
escreval("Quantos graus está hoje?")
leia(t1)
se (t1 > 26) entao
escreval("Está um dia quente!!!")
senao
escreval("Hoje não está um dia quente!!!")
fimse
Fimalgoritmo